Bio-Data/Models/ViewModel/BiodataViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Bio_Data.Models.ViewModel
{
    public class BiodataViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "* Dateoftime can't be blank.")]
        public DateTime Dateoftime { get; set; }
        [Required(ErrorMessage = "* TimeOfBirth can't be blank.")]
        [DataType(DataType.Time)]
        public DateTime TimeOfBirth { get; set; }
        [Required(ErrorMessage = "* PlaceOfBirth can't be blank.")]
        public string PlaceOfBirth { get; set; }
        [Required(ErrorMessage = "* Rasi can't be blank.")]
        public string Rasi { get; set; }
        [Required(ErrorMessage = "* Nakshtra can't be blank.")]
        public string Nakshtra { get; set; }
        [Required(ErrorMessage = "* Complexion can't be blank.")]
        public string Complexion { get; set; }
        [Required(ErrorMessage = "* Height can't be blank.")]
        public decimal Height { get; set; }
        [Required(ErrorMessage = "* Education can't be blank.")]
        public string Education { get; set; }
        [Required(ErrorMessage = "* Cast can't be blank.")]
        public string Cast { get; set; }
        [Required(ErrorMessage = "* Job can't be blank.")]
        public string Job { get; set; }

        [Required]
        public string FatherName { get; set; }
        [Required]
        public string FatherOccupation { get; set; }
        [Required]
        public string MotherName { get; set; }
        [Required]
        public string MotherOccupation { get; set; }
        [Required]
        public string ElderBrotherName { get; set; }
        [Required]
        public string ElderBrotherOccupation { get; set; }
        [Required]
        public string YoungerBrotherName { get; set; }
        [Required]
        public string YoungerBrotherOccupation { get; set; }
        [Required]
        public string ElderSisterName { get; set; }
        [Required]
        public string ElderSisterOccupation { get; set; }
        [Required]
        public string YoungerSisterName { get; set; }
        [Required]
        public string YoungerSisterOccupation { get; set; }

        public int ContactNo { get; set; }
        [Required]
        public string Address { get; set; }
        public string Path { get; set; }

        [NotMapped]
        public IFormFile ImageFile { get; set; }
    }
}

Bio-Data/Controllers/BiodataController.cs
using Bio_Data.Data;
using Bio_Data.Models;
using Bio_Data.Models.ViewModel;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Bio_Data.Controllers
{
    public class BiodataController : Controller
    {
        private readonly ApplicationContext context;
        private readonly IWebHostEnvironment environment;

        public BiodataController(ApplicationContext context, IWebHostEnvironment environment)
        {
            this.context = context;
            this.environment = environment;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult PersonalDetailsCreate()
        {
            return View();
        }
        [HttpPost]
        public IActionResult PersonalDetailsCreate(Personaldetails model)
        {
            if (ModelState.IsValid)
            {
                var personaldetails = new Personaldetails()
                {
                    Name = model.Name,
                    Dateoftime = model.Dateoftime,
                    TimeOfBirth = model.TimeOfBirth,
                    PlaceOfBirth = model.PlaceOfBirth,
                    Rasi = model.Rasi,
                    Nakshtra = model.Nakshtra,
                    Complexion = model.Complexion,
                    Height = model.Height,
                    Education = model.Education,
                    Cast = model.Cast,
                    Job = model.Job
                };
                context.personaldetails.Add(personaldetails);
                context.SaveChanges();
                TempData["error"] = "Record Submit";
                return RedirectToAction("Index", "Home");
            }
            else
            {
                TempData["message"] = "Empty field can't Submit";
                return RedirectToAction("Index", "Home");
            }
        }
        [HttpGet]
        public IActionResult FamilyDetailsCreate()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> FamilyDetailsCreate(Familydetails model)
        {
            if (ModelState.IsValid)
            {
                var familydetails = new Familydetails()
                {
                    FatherName = model.FatherName,
                    FatherOccupation = model.FatherOccupation,
                    MotherName = model.MotherName,
                    MotherOccupation = model.MotherOccupation,
                    ElderBrotherName = model.ElderBrotherName,
                    ElderBrotherOccupation = model.ElderBrotherOccupation,
                    YoungerBrotherName = model.YoungerBrotherName,
                    YoungerBrotherOccupation = model.YoungerBrotherName,
                    ElderSisterName = model.ElderSisterName,
                    ElderSisterOccupation = model.ElderSisterOccupation,
                    YoungerSisterName = model.YoungerSisterName,
                    YoungerSisterOccupation = model.YoungerSisterOccupation
                };
                  context.familydetails.Add(familydetails);
                 context.SaveChanges();
                TempData["error"] = "Record Submit";
                return RedirectToAction("Index", "Home");
            }
            else
            {
                TempData["message"] = "Empty field can't Submit";
                return RedirectToAction("Index", "Home");                           
            }
        }

        [HttpGet]
        public IActionResult ContactDetailsCreate()
        {
            return View();
        }

        [HttpPost]
        public IActionResult ContactDetailsCreate(Contactdetails model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string uniqueFileName = UploadImage(model);
                    var data = new Contactdetails()
                    {
                        ContactNo = model.ContactNo,
                        Address = model.Address,
                        Path = uniqueFileName
                    };
                    context.contactdetails.Add(data);
                    context.SaveChanges();
                    TempData["Success"] = "Record Successfuly saved!";
                    return RedirectToAction("Index","Home");
                }
                ModelState.AddModelError(string.Empty, "Model is not valid");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }

            return View("Index", "Home");
        }
        public string UploadImage(Contactdetails model)
        {
            string uniqueFileName = string.Empty;
            if (model.ImageFile != null)
            {
                string uploadfolder = Path.Combine(environment.WebRootPath, "Content/Image/");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.ImageFile.FileName;
                string filePath = Path.Combine(uploadfolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.ImageFile.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }

        [HttpPost]
        public async Task<IActionResult> SaveAllData(SubmitViewmodel obj , string command)
        {
            //string uniqueFileName = UploadImage(obj);
            if (command == "Next")
                {
                    Personaldetails personaldetails = new Personaldetails()
                    {
                        Name = obj.Name,
                        Dateoftime = obj.Dateoftime,
                        TimeOfBirth = obj.TimeOfBirth,
                        PlaceOfBirth = obj.PlaceOfBirth,
                        Rasi = obj.Rasi,
                        Nakshtra = obj.Nakshtra,
                        Complexion = obj.Complexion,
                        Height = obj.Height,
                        Education = obj.Education,
                        Cast = obj.Cast,
                        Job = obj.Job
                    };

                    context.personaldetails.Add(personaldetails);
                context.SaveChanges();
               // return RedirectToAction("EnterFamilyDetails", new { personalDetailsId = personaldetails.Id });

            } 
                else if (command == "NexT")
                {
                //int personalDetailsId = Convert.ToInt32(Request.Query["personalDetailsId"]);
                //Personaldetails personaldetails = context.personaldetails.FirstOrDefault(p => p.Id == personalDetailsId);
                //if (personaldetails == null)
                //{
                //    return RedirectToAction("_PersonalDetails");
                //}

                Familydetails familydetails = new Familydetails()
                    {
                        FatherName = obj.FatherName,
                        FatherOccupation = obj.FatherOccupation,
                        MotherName = obj.MotherName,
                        MotherOccupation = obj.MotherOccupation,
                        ElderBrotherName = obj.ElderBrotherName,
                        ElderBrotherOccupation = obj.ElderBrotherOccupation,
                        YoungerBrotherName = obj.YoungerBrotherName,
                        YoungerBrotherOccupation = obj.YoungerBrotherName,
                        ElderSisterName = obj.ElderSisterName,
                        ElderSisterOccupation = obj.ElderSisterOccupation,
                        YoungerSisterName = obj.YoungerSisterName,
                        YoungerSisterOccupation = obj.YoungerSisterOccupation
                    };
                    context.familydetails.Add(familydetails);
                    context.SaveChanges();

            }
                else if (command == "SUBMIT")
                {
                
                var data = new Contactdetails()
                {
                    ContactNo = obj.ContactNo,
                    Address = obj.Address,
                   // Path = uniqueFileName
                };
                context.contactdetails.Add(data);
                context.SaveChanges();
            }
          
            return RedirectToAction("Index", "Home");
        }


    }
}

Bio-Data/Views/Biodata/ContactDetailsCreate.cshtml
@model Bio_Data.Models.Contactdetails

@{
    ViewData["Title"] = "ContactDetailsCreate";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-6 offset-3">
            <div class="card">
                <div class="card-header">
                    <h1 class="text-center text-primary">Contact Details</h1>
                    <p class="text-center text-danger">@TempData["message"]</p>
                </div>
                <div class="card-body">
                    <form method="post" action="ContactDetailsCreate" enctype="multipart/form-data">
                        <div asp-validation-summary="ModelOnly" class="text-danger text-center"></div>
                        <div class="form-group">
                            <label asp-for="ContactNo"></label>
                            <input type="text" asp-for="ContactNo" class="form-control" placeholder="Enter Contact No" />
                        </div>
                        <div class="form-group">
                            <label asp-for="Address"></label>
                            <input type="text" asp-for="Address" class="form-control" placeholder="Enter Address" />
                        </div>
                        <div>
                            <label asp-for="ImageFile"></label>
                            <input type="file" class="form-control" asp-for="ImageFile" id="ChooseImg" />
                        </div><br>
                        <div>
                            <input type="submit" class="btn btn-sm btn-outline-success float-right" value="SUBMIT" />
                            <a asp-action="FamilyDetailsCreate" asp-controller="Biodata">Back</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Bio-Data/Views/Biodata/FamilyDetailsCreate.cshtml
@model Bio_Data.Models.Familydetails
@{
    ViewData["Title"] = "FamilyDetailsCreate";
}

<div class="container">
    <div class="row">
        <div class="col-8 offset-2">
            <div class="card">
                <div class="card-header">
                    <h1 class="text-center text-primary">Family Details</h1>
                    <p class="text-center text-danger">@TempData["message"]</p>
                </div>
                <div class="card-body">
                    <form method="post" action="FamilyDetailsCreate">
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <label asp-for="FatherName">Father-Name</label>
                                    <input type="text" asp-for="FatherName" class="form-control" placeholder="Enter Father-Name" />
                                    <span asp-validation-for="FatherName" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    <label asp-for="FatherOccupation">Father-Occupation</label>
                                    <input type="text" asp-for="FatherOccupation" class="form-control" placeholder="Enter Father-Occupation" />
                                    <span asp-validation-for="FatherOccupation" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <label asp-for="MotherName">Mother-Name</label>
                                    <input type="text" asp-for="MotherName" class="form-control" placeholder="Enter Mother-Name" />
                                    <span asp-validation-for="MotherName" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    <label asp-for="MotherOccupation">Mother-Occupation</label>
                                    <input type="text" asp-for="MotherOccupation" class="form-control" placeholder="Enter Mother-Occupation" />
                                    <span asp-validation-for="MotherOccupation" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <label asp-for="ElderBrotherName">ElderBrother-Name</label>
                                    <input type="text" asp-for="ElderBrotherName" class="form-control" placeholder="Enter Elder-Brother-Name" />
                                    <span asp-validation-for="ElderBrotherName" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    <label asp-for="ElderBrotherOccupation">ElderBrother-Occupation</label>
                                    <input type="text" asp-for="ElderBrotherOccupation" class="form-control" placeholder="Enter Elder-Brother-Occupation" />
                                    <span asp-validation-for="ElderBrotherOccupation" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <label asp-for="YoungerBrotherName">YoungerBrother-Name</label>
                                    <input type="text" asp-for="YoungerBrotherName" class="form-control" placeholder="Enter Younger-Brother-Name" />
                                    <span asp-validation-for="YoungerBrotherName" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    <label asp-for="YoungerBrotherOccupation">YoungerBrother-Occupation</label>
                                    <input type="text" asp-for="YoungerBrotherOccupation" class="form-control" placeholder="Enter Younger-Brother-Occupation" />
                                    <span asp-validation-for="YoungerBrotherOccupation" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <label asp-for="ElderSisterName">ElderSister-Name</label>
                                    <input type="text" asp-for="ElderSisterName" class="form-control" placeholder="Enter Elder-Sister-Name" />
                                    <span asp-validation-for="ElderSisterName" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    <label asp-for="ElderSisterOccupation">ElderSister-Occupation</label>
                                    <input type="text" asp-for="ElderSisterOccupation" class="form-control" placeholder="Enter Elder-Sister-Occupation" />
                                    <span asp-validation-for="ElderSisterOccupation" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <label asp-for="YoungerSisterName">YoungerSister-Name</label>
                                    <input type="text" asp-for="YoungerSisterName" class="form-control" placeholder="Enter Younger-Sister-Name" />
                                    <span asp-validation-for="YoungerSisterName" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    <label asp-for="YoungerSisterOccupation">YoungerSister-Occupation</label>
                                    <input type="text" asp-for="YoungerSisterOccupation" class="form-control" placeholder="Enter Younger-Sister-Occupation" />
                                    <span asp-validation-for="YoungerSisterOccupation" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Next" class="btn btn-lg btn-outline-success float-right" data-toggle="collapse" data-target="#collapseThree" />|
                            <a asp-action="PersonalDetailsCreate">Back</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Bio-Data/Views/Biodata/PersonalDetailsCreate.cshtml
@model Bio_Data.Models.Personaldetails

@{
    ViewData["Title"] = "PersonalDetailsCreate";
}

<div class="container">
    <div class="row">
        <div class="col-8 offset-2">
            <div class="card">
                <div class="card-header">
                    <h1 class="text-center text-primary">Personal Details</h1>
                    <p class="text-center text-danger">@TempData["message"]</p>
                </div>
                <div class="card-body">
                    <form method="post">
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <label asp-for="Name">Name</label>
                                    <input type="text" asp-for="Name" class="form-control" placeholder="Enter Name" />
                                    <span asp-validation-for="Name" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    <label asp-for="Dateoftime">Date-Of-Birth</label>
                                    <input asp-for="Dateoftime" class="form-control" placeholder="Enter Date Of Birth" />
                                    <span asp-validation-for="Dateoftime" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <label asp-for="TimeOfBirth">Time-Of-Birth</label>
                                    <input asp-for="TimeOfBirth" class="form-control" placeholder="Enter Time-Of-Birth" />
                                    <span asp-validation-for="TimeOfBirth" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    <label asp-for="PlaceOfBirth">Place-Of-Birth</label>
                                    <input type="text" asp-for="PlaceOfBirth" class="form-control" placeholder="Enter Place-Of-Birth" />
                                    <span asp-validation-for="PlaceOfBirth" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <label asp-for="Rasi" class="control-label">Rashi</label>
                                    <select type="text" asp-for="Rasi" class="form-control" asp-items="ViewBag.Rasi">
                                    <option value="">-- Select Rashi --</option>
                                    <option value="Mesh Rashi">Mesh Rashi</option>
                                    <option value="Vrishabh Rashi">Vrishabh Rashi</option>
                                    <option value="Mithun Rashi">Mithun Rashi</option>
                                        </select>
                                    <span asp-validation-for="Rasi" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    <label asp-for="Nakshtra" class="control-label">Nakshtra</label>
                                    <input type="text" asp-for="Nakshtra" class="form-control" placeholder="Enter Nakshtra" />
                                    <span asp-validation-for="Nakshtra" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <label asp-for="Complexion">Complexion</label>
                                    <input type="text" asp-for="Complexion" class="form-control" placeholder="Enter Complexion" />
                                    <span asp-validation-for="Complexion" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    <label asp-for="Height">Height</label>
                                    <input type="text" asp-for="Height" class="form-control" placeholder="Enter Height" />
                                    <span asp-validation-for="Height" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <label asp-for="Education">Education</label>
                                    <input type="text" asp-for="Education" class="form-control" placeholder="Enter Education" />
                                    <span asp-validation-for="Education" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    <label asp-for="Cast">Cast</label>
                                    <input type="text" asp-for="Cast" class="form-control" placeholder="Enter Cast" />
                                    <span asp-validation-for="Cast" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="Job">Job</label>
                            <input type="text" asp-for="Job" class="form-control" placeholder="Enter Education" />
                            <span asp-validation-for="Job" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Next" class="btn btn-lg btn-outline-success float-right" />|
                            <a asp-action="Index" asp-controller="Home">Back</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>